---
title: "Adolescent placement analysis"
output: html_notebook
---

```{r data }
df <- read.delim('../data/raw/APS/APS.txt')
```

```{r}
df <- transform( df
                 , ID = factor( ID )
                 , PLACE = factor( PLACE
                                   , levels = c( 0, 1, 2, 3 )
                                   , labels = c( 'Outpatient', 'Day treatment', 'Intermediate residential', 'Residential' )
                                   )
                 , PLACE3 = factor( PLACE3
                                    , levels = c( 0, 1, 2 )
                                    , labels = c( 'Outpatient or day tx', 'Intermediate residential', 'Residential' )
                                    )
                 , AGE = AGE
                 , RACE = factor( RACE 
                                  , levels = c( 0, 1 )
                                  , labels = c( 'White', 'Non-white' )
                                  )
                 , GENDER = factor( GENDER
                                    , levels = c( 0, 1 )
                                    , labels = c( 'Female', 'Male' )
                                    )
                 , NEURO = factor( NEURO
                                   , levels = c( 0, 1, 2, 3 )
                                   , labels = c( 'None', 'Mild', 'Moderate' ,'Severe' )
                                   )
                 , EMOT = factor( EMOT
                                  , levels = c( 0, 1 )
                                  , labels = c( 'Not severe', 'Severe' )
                                  )
                 , DANGER = factor( DANGER 
                                    , levels = c( 0, 1, 2, 3 )
                                    , labels = c( 'Unlikely', 'Possible', 'Probable', 'Likely' )
                                    )
                 , ELOPE = factor( ELOPE 
                                   , levels = c( 0, 1 )
                                   , labels = c( 'No risk', 'At risk' )
                                   )
                 , LOS = LOS
                 , BEHAV = BEHAV
                 , CUSTD = factor( CUSTD
                                   , levels = c( 0, 1 )
                                   , labels = c( 'No', 'Yes' )
                                   )
                 , VIOL = factor( VIOL
                                  , levels = c( 0, 1 )
                                  , labels = c( 'No', 'Yes' ) 
                                  )
                 )
```

