---
title: "ICU analysis"
output: 
  html_notebook:
    smart: false
---

## Load data
```{r data}
df <- read.delim('../data/ICU.txt')
```

```{r}
df <- transform( df
                 , ID = ID
                 , STA = factor( STA
                                 , levels = c( 0, 1 )
                                 , labels = c( 'Died', 'Lived' ) )
                 , AGE = AGE
                 , GENDER = factor( GENDER
                                    , levels = c( 0, 1 )
                                    , labels = c( 'Male', 'Female' ) )
                 , RACE = factor( RACE
                                  , levels = c( 1, 2, 3 )
                                  , labels = c( 'White', 'Black', 'Other' ) )
                 , SER = factor( SER
                                 , levels = c( 0, 1 )
                                 , labels = c( 'Medical', 'Surgical' ) )
                 , CAN = factor( CAN 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'Cancer not present', 'Cancer present' ) 
                                 )
                 , CRN = factor( CRN 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'No hx of CRF', 'Has h of CRF' ) 
                                 )
                 , INF = factor( INF 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'No infection at admission', 'Probable infection at admission' )
                                 )
                 , CPR = factor( CPR
                                 , levels = c( 0, 1 )
                                 , labels = c( 'No CPR given', 'CPR given' )
                                 )
                 , SYS = SYS 
                 , HRA = HRA
                 , PRE = factor( PRE 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'No prev ICU adx', 'Has prev ICU adx' )
                                 )
                 , TYP = factor( TYP
                                  , levels = c( 0, 1 )
                                  , labels = c( 'Elective', 'Emergency' )
                                  )
                 , FRA = factor( FRA 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'No fracture', 'Has fracture' )
                                 )
                 , PO2 = factor( PO2 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'PO2 > 60', 'PO2 <= 60' )
                                 )
                 , PH = factor( PH 
                                , levels = c( 0, 1 )
                                , labels = c( 'PH >= 7.25', 'PH < 7.25' )
                                )
                 , PCO = factor( PCO 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'PCO2 <= 45', 'PCO2 > 45' )
                                 )
                 , BIC = factor( BIC 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'Bicarb >= 18', 'Bicarb < 18' )
                                 )
                 , CRE = factor( CRE 
                                 , levels = c( 0, 1 )
                                 , labels = c( 'Creatinine <= 2.0', 'Creatinine > 2.0' )
                                 )
                 , LOC = factor( LOC
                                 , levels = c( 0, 1, 2 )
                                 , labels = c( 'No coma or DS', 'Deep stupor', 'Coma' )
                                 )
                 
                                 
                 )
```

```{r}
str(df)
```

```{r null }
icu.null.fit <- glm( df$STA
                ~ 1
                , family = 'binomial' )
summary( icu.null.fit )
```
### This is fit automatically in the GLM with the variable(s) of interest.

```{r univ }
icu.age.fit <- glm( STA
                    ~ AGE
                    , data = df
                    , family = 'binomial' )
summary( icu.age.fit )
```

```{r}
anova( icu.age.fit
      , test = 'Chisq' )
```

```{r mult }
icu.age.fit <- glm( STA
                    ~ AGE
                    + INF
                    , data = df
                    , family = 'binomial' )
summary( icu.age.fit )
```

```{r}
icu.age.fit <- glm( STA
                    ~ AGE
                    , data = df
                    , family = 'binomial' )
summary( icu.age.fit )
```

```{r coef }
exp( coef( icu.age.fit ) )
```

```{r confint }
exp( confint( icu.age.fit ) )
```


```{r}
df$AGE_CUT <- cut( df$AGE
     , breaks = c( 15, 25, 35, 45, 55, 65, 75, 85, 95 ) )
```

```{r}
ggplot( df ) +
  geom_point( aes( x = STA, y = AGE_CUT ) ) +
  theme_bw()
```

```{r}
prop.table( table( df$STA, df$AGE_CUT  ), 2 )
```

```{r}
a <- c( 0.93, 1, 0.82, 0.81, 0.74, 0.78, 0.78, 0.60 )
b <- c( 1, 25, 37.5, 50, 62.5, 75, 87.5, 100 )
ggplot( data.frame( cbind( a, b ) ) ) +
  geom_point( aes( x = b, y = a ) ) +
  ylim( 0, 1 ) +
  theme_bw()
```

```{r fitted values }
di <- di <- data.frame( cbind( df$AGE                          
                               , ( exp( -3.23062+0.02387 * df$AGE ) ) 
                               / ( 1+( exp( -3.23062 + 0.02387 * df$AGE ) ) ) ) )

a <- c( 0.93, 1, 0.82, 0.81, 0.74, 0.78, 0.78, 0.60 )
b <- c( 0, 25, 37.5, 50, 62.5, 75, 87.5, 100 )
dj <- data.frame( cbind( a, b ) )

ggplot( ) +
  geom_point( aes( x = dj$b, y = dj$a ) ) +
  geom_line( aes( x = di$X1, y = 1 - di$X2 ), colour = 'red', alpha = .5) +
  ylim( 0, 1 ) +
  theme_bw()
```

```{r lrt}
lrtest( glm( df$STA 
             ~ 1
             , family = binomial( link = 'logit' )
             )
        , glm( df$STA
               ~ df$AGE
               , family = binomial( link = 'logit' )
               )
        )
```

```{r wald }
waldtest( glm( df$STA 
             ~ 1
             , family = binomial( link = 'logit' )
             )
        , glm( df$STA
               ~ df$AGE
               , family = binomial( link = 'logit' )
               )
        )
```

